alias ls='lsd'
alias ll='lsd -l'
alias la='lsd -a'
alias lla='lsd -la'
alias cl='clear'
alias t='touch'
alias sys='sudo systemctl'
alias v='nvim'
alias sv='sudo vim'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -v'
alias wh='which'
alias '?'='which'
alias se='sudoedit'
alias tf='printf "%s-%s" $(date -I | sed "s/-//g") $(date "+%H%M%S")'
alias ob='objdump -dSwCsMaddr64,intel --no-show-raw-insn'
alias cg++='g++ -std=c++23 -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Wunused -O3'
alias cclang++='clang++ -std=c++23 -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Wunused -O3 -stdlib=libc++'
alias ydl='yt-dlp -x --audio-format best --audio-quality 0'
alias ins='instaloader --no-videos --no-video-thumbnails --no-captions --no-metadata-json'
alias x='exit'
alias smt='objdump -t'
